version: '3.9'  # Atualize a versão para uma recente

services:
  db:
    build: ./db
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: datadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sysbipass**++
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  credapp:
    build: ./credapp
    container_name: credapp
    environment:
      DB_HOST: db
      DB_NAME: datadb
      DB_USER: admin
      DB_PASSWORD: sysbipass**++
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace/credapp
    networks:
      - app-network

  datasys:
    build: ./datasys
    container_name: datasys
    environment:
      DB_HOST: db
      DB_NAME: datadb
      DB_USER: admin
      DB_PASSWORD: sysbipass**++
    ports:
      - "5001:5001"
    volumes:
      - .:/workspace/datasys
    networks:
      - app-network

  alembic:
    image: python:3.9
    working_dir: /workspace/credapp
    volumes:
      - .:/workspace
    environment:
      DB_HOST: db
      DB_NAME: datadb
      DB_USER: admin
      DB_PASSWORD: sysbipass**++
    command: bash -c "pip install -r requirements.txt && alembic init migrations"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
